### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by RobertVDK** [flagshipcompany/flagship-for-opencart#1] opened 2019-11-27 15:55 UTC
After installing properly, inlcuding mod refresh....when clicking "install" on the shipping module, we get:

Parse error: syntax error, unexpected '?' in /home/XXXXXXXXXX/public_html/admin/controller/extension/shipping/flagship.php on line 243

Uninstalling gives same result.

**Comment by radua** [comment] 2019-11-27 17:59
Hi @RobertVDK,
Thank you for reporting the issue. However, I am not able to reproduce it on my end. Can you please share PHP version that you are using.
I have tried installing it on an Ubuntu Server 18.04 with PHP 7.2. However, the plugin is compatible with PHP 7.1 and upwards.

**Comment by RobertVDK** [comment] 2019-11-27 18:01
PHP 7.1

Note, that the composer files installed fine. The extension uploaded fine
into opencart. When clicking install on the extension -> shipping
extension, we receive the error.

**Comment by radua** [comment] 2019-11-27 18:11
Do you get the configuration page? If so, are you able to save the token? If not, can you please share the stack trace. Thanks

**Comment by RobertVDK** [comment] 2019-11-27 18:18
Even the order page we can't view now
[image: image.png]
Extension shows not installed:
[image: image.png]

I've deleted the install completely now, to get our system back.

**Comment by radua** [comment] 2019-11-27 18:51
I tried installing Opencart 3.0.3.1 with PHP 7.1 and installed the plugin (version 1.0.1). Unfortunately, I was not able to reproduce the error. Kindly share the logs.
Thanks

**Comment by radua** [comment] 2019-12-04 20:14
Hi @RobertVDK , Please check our new release of flagship-for-opencart and let us know if you still face the issue.

**Comment by RobertVDK** [comment] 2019-12-04 20:19
Hello.

I don't think flagship-for-magento will help, since we run Opencart.

**Comment by radua** [comment] 2019-12-04 20:38
@RobertVDK , Apologies, I meant to point to our latest release of flagship-for-opencart.

**Comment by RobertVDK** [comment] 2019-12-04 21:03
We've tried to install. It installs, but doesn't show up in our extensions
under shipping after cache clearing and rebuilding of modifications.

I think that was our last attempt with this module.

Thanks

**Comment by radua** [comment] 2019-12-05 13:37
Closed as unable to reproduce.

**Closed as completed by radua** 2019-12-05 13:37 UTC
